CREATE TABLE LIBROS(
    IDLIBRO NUMBER PRIMARY KEY,
    AUTOR VARCHAR2(30),
    TITULO VARCHAR2(50),
    CANTIDAD NUMBER,
    ANIO NUMBER,
    EDITORIAL VARCHAR2(30),
    PAIS VARCHAR2(30),
    PRECIO NUMBER(8,2),
    ESTADO VARCHAR2(1)
);

CREATE SEQUENCE SQL_LIBROS
START WITH 1
INCREMENT BY 1
MINVALUE 1
NOCYCLE;

COMMIT;

INSERT INTO LIBROS VALUES(SQL_LIBROS.NEXTVAL,'Flor Cerdán','Oracle 11g',10,2019,'IEU','Peru',50,'A');
INSERT INTO LIBROS VALUES(SQL_LIBROS.NEXTVAL,'Omar Peña','Sistemas Operativos',14,2016,'Lima Sur','Peru',59,'A');
INSERT INTO LIBROS VALUES(SQL_LIBROS.NEXTVAL,'Omar Peña','Estructura de Datos',6,2018,'Macro','Argentina',20,'A');
INSERT INTO LIBROS VALUES(SQL_LIBROS.NEXTVAL,'Flor Cerdán','Algoritmos con Python',8,2017,'Macro','Argentina',70,'A');
INSERT INTO LIBROS VALUES(SQL_LIBROS.NEXTVAL,'Daniel Levano','BI',6,1998,'Lima Sur','Peru',50,'A');
INSERT INTO LIBROS VALUES(SQL_LIBROS.NEXTVAL,'Cesar Zapata','Ing. de Software',9,2000,'Macro','Colombia',56,'A');
INSERT INTO LIBROS VALUES(SQL_LIBROS.NEXTVAL,'Flor Cerdán','Organización de PC',9,2016,'Macro','USA',60,'A');
INSERT INTO LIBROS VALUES(SQL_LIBROS.NEXTVAL,'Omar Peña','Ensamblaje',9,2018,'Lima Sur','Venezuela',50,'A');
INSERT INTO LIBROS VALUES(SQL_LIBROS.NEXTVAL,'Daniel Levano','Redes',5,2017,'Pirámide','Ecuador',77,'A');
INSERT INTO LIBROS VALUES(SQL_LIBROS.NEXTVAL,'Cesar Zapata','Tesis',7,2009,'Bosch','España',100,'A');
INSERT INTO LIBROS VALUES(SQL_LIBROS.NEXTVAL,'Flor Cerdán','Seguridad de TI',12,2007,'Pirámide','Rusia',60,'A');
INSERT INTO LIBROS VALUES(SQL_LIBROS.NEXTVAL,'Daniel Levano','Algoritmos con Java',20,2019,'IEU','Peru',40,'A');
INSERT INTO LIBROS VALUES(SQL_LIBROS.NEXTVAL,'Cesar Zapata','Gestión de Proyectos',22,2016,'Pirámide','Peru',50,'A');
INSERT INTO LIBROS VALUES(SQL_LIBROS.NEXTVAL,'Cesar Zapata','FEPI',25,2005,'Lima Sur','Argentina',80,'A');
INSERT INTO LIBROS VALUES(SQL_LIBROS.NEXTVAL,'Omar Peña','Estadistica',27,2017,'Lima Sur','Colombia',60,'A');
INSERT INTO LIBROS VALUES(SQL_LIBROS.NEXTVAL,'Flor Cerdán','Aplicaciones Móviles',6,2009,'Lima Sur','USA',50,'A');
INSERT INTO LIBROS VALUES(SQL_LIBROS.NEXTVAL,'Cesar Zapata','Calculo III',8,2007,'Pirámide','Venezuela',80,'A');
INSERT INTO LIBROS VALUES(SQL_LIBROS.NEXTVAL,'Omar Peña','Métodos Numéricos',4,2000,'Pirámide','Ecuador',60,'A');
INSERT INTO LIBROS VALUES(SQL_LIBROS.NEXTVAL,'Daniel Levano','Scrum',23,1999,'Bosch','España',50,'A');
INSERT INTO LIBROS VALUES(SQL_LIBROS.NEXTVAL,'Omar Peña','Sistemas Operativos',66,2000,'Lima Sur','Rusia',100,'A');
INSERT INTO LIBROS VALUES(SQL_LIBROS.NEXTVAL,'Cesar Zapata','Calculo III',7,2019,'Lima Sur','Peru',50,'A');
INSERT INTO LIBROS VALUES(SQL_LIBROS.NEXTVAL,'Cesar Zapata','Seguridad de TI',6,2016,'Macro','Argentina',80,'A');
INSERT INTO LIBROS VALUES(SQL_LIBROS.NEXTVAL,'Omar Peña','Algoritmos con Java',8,2018,'Macro','Colombia',60,'A');
INSERT INTO LIBROS VALUES(SQL_LIBROS.NEXTVAL,'Flor Cerdán','Gestión de Proyectos',4,2017,'Lima Sur','USA',50,'A');
INSERT INTO LIBROS VALUES(SQL_LIBROS.NEXTVAL,'Cesar Zapata','FEPI',9,1998,'Pirámide','Venezuela',80,'A');
INSERT INTO LIBROS VALUES(SQL_LIBROS.NEXTVAL,'Omar Peña','Estadistica',4,2000,'Bosch','Ecuador',60,'A');
INSERT INTO LIBROS VALUES(SQL_LIBROS.NEXTVAL,'Daniel Levano','Aplicaciones Móviles',5,1998,'Pirámide','España',50,'A');
INSERT INTO LIBROS VALUES(SQL_LIBROS.NEXTVAL,'Omar Peña','Calculo III',1,2000,'IEU','Rusia',100,'A');

SELECT * FROM LIBROS;

CREATE TABLE AUTOR(
    IDAUTOR NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(30),
    F_NACIMIENTO DATE
);
CREATE SEQUENCE sq_autor
START WITH 1
INCREMENT BY 1
MINVALUE 1
NOCYCLE;

CREATE TABLE EDITORIAL(
    IDEDITORIAL     NUMBER PRIMARY KEY,
    NOMBRE          VARCHAR(30),
    ESTADO          VARCHAR(1)
);
CREATE SEQUENCE sq_editorial
START WITH 1
INCREMENT BY 1
MINVALUE 1
NOCYCLE;

CREATE TABLE PAIS(
    IDPAIS     NUMBER PRIMARY KEY,
    NOMBRE     VARCHAR(30),
    ESTADO     VARCHAR(1)
);

CREATE SEQUENCE sq_pais
START WITH 1
INCREMENT BY 1
MINVALUE 1
NOCYCLE;

CREATE TABLE LIBRO(
    IDLIBRO     NUMBER PRIMARY KEY,
    TITULO      VARCHAR2(30),
    CANTIDAD    NUMBER,
    ANIO        NUMBER,
    PRECIO      NUMBER(8,2),
    ESTADO      VARCHAR2(1),
    IDAUTOR     NUMBER REFERENCES AUTOR,
    IDEDITORIAL NUMBER REFERENCES EDITORIAL,
    IDPAIS      NUMBER REFERENCES PAIS
);

CREATE SEQUENCE SQ_LIBRO
START WITH 1
INCREMENT BY 1
MINVALUE 1
NOCYCLE;

INSERT INTO AUTOR VALUES(SQ_AUTOR.NEXTVAL,'FLOR CERDAN','25/10/78');
INSERT INTO AUTOR VALUES(SQ_AUTOR.NEXTVAL,'DANIEL LEVANO','17/01/80');
INSERT INTO AUTOR VALUES(SQ_AUTOR.NEXTVAL,'OMAR PEÑA','15/10/78');
INSERT INTO AUTOR VALUES(SQ_AUTOR.NEXTVAL,'CESAR ZAPATA','15/10/60');

INSERT INTO PAIS VALUES(SQ_PAIS.NEXTVAL,'PERU','A');
INSERT INTO PAIS VALUES(SQ_PAIS.NEXTVAL,'ARGENTINA','A');
INSERT INTO PAIS VALUES(SQ_PAIS.NEXTVAL,'COLOMBIA','A');
INSERT INTO PAIS VALUES(SQ_PAIS.NEXTVAL,'VENEZUELA','A');
INSERT INTO PAIS VALUES(SQ_PAIS.NEXTVAL,'URUGUAY','A');
INSERT INTO PAIS VALUES(SQ_PAIS.NEXTVAL,'PARAGUAY','A');
INSERT INTO PAIS VALUES(SQ_PAIS.NEXTVAL,'USA','A');

INSERT INTO EDITORIAL VALUES(SQ_EDITORIAL.NEXTVAL,'EIU','A');
INSERT INTO EDITORIAL VALUES(SQ_EDITORIAL.NEXTVAL,'MACRO','A');
INSERT INTO EDITORIAL VALUES(SQ_EDITORIAL.NEXTVAL,'BOSCH','A');
INSERT INTO EDITORIAL VALUES(SQ_EDITORIAL.NEXTVAL,'LIMA SUR','A');
INSERT INTO EDITORIAL VALUES(SQ_EDITORIAL.NEXTVAL,'PIRAMIDE','A');
INSERT INTO EDITORIAL VALUES(SQ_EDITORIAL.NEXTVAL,'COLOMBUS','A');
INSERT INTO EDITORIAL VALUES(SQ_EDITORIAL.NEXTVAL,'CENTRO','A');

SELECT * FROM EDITORIAL;

INSERT INTO LIBRO VALUES(SQ_LIBRO.NEXTVAL,'ORACLE 11G',10,2019,50,'A',1,1,1);
INSERT INTO LIBRO VALUES(SQ_LIBRO.NEXTVAL,'SIATEMAS OPERATIVOS',14,2016,59,'A',1,4,3);
INSERT INTO LIBRO VALUES(SQ_LIBRO.NEXTVAL,'ESTRUCTURA DE DATOS',6,2018,20,'A',2,2,3);
INSERT INTO LIBRO VALUES(SQ_LIBRO.NEXTVAL,'ALGORITMOS CON PYTHON',8,2017,70,'A',2,2,1);
INSERT INTO LIBRO VALUES(SQ_LIBRO.NEXTVAL,'BI',6,1998,50,'A',1,4,2);
INSERT INTO LIBRO VALUES(SQ_LIBRO.NEXTVAL,'ING. DE SOFTWARE',9,2000,56,'A',3,2,4);

INSERT INTO LIBRO VALUES(SQ_LIBRO.NEXTVAL,'ENSAMBLAJE',9,2018,50,'A',4,4,3);
SELECT * FROM LIBRO;

SELECT
    L.TITULO,
    L.CANTIDAD,
    L.ANIO AÑO,
    A.NOMBRE AUTOR,
    E.NOMBRE EDITORIAL,
    P.NOMBRE PAIS
FROM
    AUTOR A,
    PAIS P,
    EDITORIAL E,
    LIBRO L
WHERE
    A.IDAUTOR   = L.IDAUTOR AND
    P.IDPAIS    = L.IDPAIS AND
    E.IDEDITORIAL=L.IDEDITORIAL 
ORDER BY L.TITULO;
